import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from "next/font/google"
import Navbar from "./component/layout/Navbar";
import Footer from "./component/layout/Footer";
import Topbar from "./component/layout/Topbar";
import LoaderWrapper from "./component/sections/LoaderWrapper";
import ScrollButton from "./component/ui/ScrollButton";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={outfit.className}>
      <body className=" overflow-y-scroll scrollbar-custom">
        <LoaderWrapper>
          <div className=" md:py-4.5 md:px-12.5 px-3 py-10 2xl:gap-20 gap-15 max-md:gap-12.5 flex flex-col  min-h-screen  ">
            <div>
              <Topbar />
              <Navbar />
            </div>
            {children}
            <Footer />
            <ScrollButton/>
          </div>
        </LoaderWrapper>
      </body>
    </html>
  );
}
